name       : haskell-resource-pool
version    : 0.2.3.2
release    : 1
source     :
    - http://hackage.haskell.org/package/resource-pool-0.2.3.2/resource-pool-0.2.3.2.tar.gz : 8627eea2bea8824af2723646e74e2af0c73f583dd0c496c9fd242cd9d242bc12
license    : BSD-3-Clause
component  : programming.haskell
summary    : A high-performance striped pooling abstraction for managing flexibly-sized collections of resources such as database connections.
description: |
    A high-performance striped pooling abstraction for managing flexibly-sized collections of resources such as database connections.
builddeps  :
    - haskell-cabal-install
    - haskell-monad-control
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
